### PR TITLE
fix(vdma): build on kernel >= 6.16 (del_timer_sync removed)

### PR DESCRIPTION
**Pull request by ilpanich**
## Problem

Building the PCIe driver fails on recent kernels (reproduced on the Raspberry Pi `6.18.33+rpt-rpi-2712` kernel):

\`\`\`
../vdma/monitor.c: In function 'hailo_vdma_monitor_stop':
../vdma/monitor.c:53:5: error: implicit declaration of function 'del_timer_sync' [-Wimplicit-function-declaration]
   53 |     del_timer_sync(&monitor->timer);
      |     ^~~~~~~~~~~~~~
\`\`\`

`del_timer_sync()` was renamed to `timer_delete_sync()` in Linux 6.2, and the legacy `del_timer_sync()` wrapper was **removed entirely in Linux 6.16**. On kernels >= 6.16 the call is an implicit declaration, which is fatal under the driver's `-Werror`.

## Fix

- Add a version-gated `del_timer_sync_compat` macro to `linux/utils/compact.h` (alongside the existing kernel-compat shims): maps to `timer_delete_sync()` on kernels >= 6.2 and to `del_timer_sync()` on older kernels.
- Use `del_timer_sync_compat()` in `linux/vdma/monitor.c`, and include `utils/compact.h` there (same include path already used by `linux/vdma/memory.c`).

Both `hailo1x_pci` and `hailo_integrated_nnc` compile `monitor.o`, so the fix covers both modules. No behavior change on supported kernels — only the symbol name is selected by kernel version.

## Testing

- Builds cleanly under `-Werror` on kernel 7.0 (exercises the `timer_delete_sync` branch).
- Confirmed building successfully on the Raspberry Pi `6.18.33+rpt-rpi-2712` kernel where the error originally occurred.

---

This fix was authored by Claude (Anthropic's Claude Code) under my supervision and review.

### CODE REVIEW

**Comment by sldunn** [comment]
Success report:
Got Hailo-10H working on Raspberry Pi 5 (kernel 6.18.34) by applying the fix from this PR + installing hailort-pcie-driver_5.3.0_all.deb + hailort_5.3.0_arm64.deb.
The driver now loads and hailortcli scan detects the device successfully.
Tested on Raspberry Pi OS (Trixie).
Would be great if this (or a similar fix) gets merged so others don’t have to manually build.
